// ============================================================================
// XLSX ENTERPRISE REPORT EXPORT — Reusable workbook builder (SheetJS)
// ============================================================================
//
// Provides a standardised enterprise report format:
//   - Summary sheet with branding, metadata, KPIs
//   - Data sheets with formatted headers, frozen pane, auto-filter
//   - Analytics sheets for trend/Pareto/KPI tables
//
// All exports use SheetJS (xlsx) already installed in the project.

import * as XLSX from 'xlsx';
import { createLogger } from '@/lib/logger';

const logger = createLogger('reportExportXlsx');

// ============================================================================
// TYPES
// ============================================================================

/** Column definition for a data sheet — drives header labels, widths, formatting */
export interface ReportColumn {
  key: string;
  header: string;
  width?: number; // character width, default 15
  format?: 'date' | 'datetime' | 'number' | 'currency' | 'percentage' | 'text';
}

/** Options for creating a standard workbook */
export interface CreateWorkbookOptions {
  /** Report title shown on the Summary sheet */
  reportName: string;
  /** Human-readable description */
  description?: string;
  /** Plant / site name (from plant table or user selection) */
  plantName?: string;
  /** Plant ID (for reference) */
  plantId?: string;
  /** Active filter values applied to the report */
  filters?: Record<string, string | undefined>;
  /** Name / email of the user generating the report */
  generatedBy: string;
  /** KPI metrics shown on the Summary sheet */
  kpis?: Array<{ label: string; value: string | number }>;
  /** Company name (defaults to 'iAssetsPro EAM') */
  companyName?: string;
}

/** Options passed when adding a data sheet */
export interface AddDataSheetOptions {
  /** Freeze the top row + N left columns? Default true */
  freezeHeader?: boolean;
  /** Number of left columns to freeze (default 0) */
  freezeColumns?: number;
  /** Enable auto-filter on headers? Default true */
  autoFilter?: boolean;
  /** Stripe alternating row colours (light grey / white). Default true */
  stripeRows?: boolean;
  /** Default column width when not specified in ReportColumn */
  defaultWidth?: number;
}

/** A single row for analytics — keys map to column headers */
export type AnalyticsRow = Record<string, string | number | boolean | null | undefined>;

/** Options for analytics sheet */
export interface AddAnalyticsOptions {
  /** Enable auto-filter */
  autoFilter?: boolean;
}

// ============================================================================
// HELPERS — cell-level formatting
// ============================================================================

/**
 * Format a Date (or date string) as `YYYY-MM-DD`.
 * Passes through null/undefined/empty strings unchanged.
 */
export function formatDate(val: unknown): string | number {
  if (val == null || val === '') return '';
  const d = val instanceof Date ? val : new Date(String(val));
  if (isNaN(d.getTime())) return String(val);
  // Return an Excel serial date number so Excel recognises it as a date
  return XLSX.SSF.parse_date_code(
    XLSX.SSF.format_date(
      'yyyy\\-mm\\-dd',
      { D: d.getDate(), T: d.getHours(), Y: d.getFullYear(), H: 0, M: d.getMonth() + 1, S: 0 },
    ),
  ) ? XLSX.SSF.format('yyyy-mm-dd', d) : String(val);
}

/**
 * Format a number with configurable decimal places.
 */
export function formatNumber(val: unknown, decimals: number = 2): string | number {
  if (val == null || val === '') return '';
  const n = Number(val);
  if (isNaN(n)) return String(val);
  return Number(n.toFixed(decimals));
}

/**
 * Format a currency value.
 */
export function formatCurrency(val: unknown): string | number {
  if (val == null || val === '') return '';
  const n = Number(val);
  if (isNaN(n)) return String(val);
  return Number(n.toFixed(2));
}

/**
 * Format a percentage value (0-100 or 0-1).
 * If the value is <= 1, it is treated as a ratio and multiplied by 100.
 */
export function formatPercentage(val: unknown): string | number {
  if (val == null || val === '') return '';
  const n = Number(val);
  if (isNaN(n)) return String(val);
  const pct = n <= 1 ? n * 100 : n;
  return `${pct.toFixed(1)}%`;
}

// ============================================================================
// CORE — createStandardWorkbook
// ============================================================================

/**
 * Create a workbook pre-populated with a "Summary" sheet containing:
 * - Company / app branding
 * - Report name & description
 * - Plant & filter metadata
 * - Generated date/time
 * - Generated by
 * - KPI summary row
 *
 * Returns the XLSX.WorkBook ready for `addDataSheet` / `addAnalyticsSheet`.
 */
export function createStandardWorkbook(options: CreateWorkbookOptions): XLSX.WorkBook {
  const wb = XLSX.utils.book_new();
  const companyName = options.companyName || 'iAssetsPro EAM';
  const now = new Date();

  // Build summary rows
  const rows: Array<Array<string>> = [];

  // Branding header
  rows.push([companyName]);
  rows.push(['Enterprise Asset Management']);
  rows.push([]);

  // Report metadata
  rows.push(['Report:', options.reportName]);
  if (options.description) {
    rows.push(['Description:', options.description]);
  }
  rows.push([]);

  // Plant
  rows.push(['Plant:', options.plantName || 'All Plants']);
  if (options.plantId) {
    rows.push(['Plant ID:', options.plantId]);
  }
  rows.push([]);

  // Filters
  if (options.filters && Object.keys(options.filters).length > 0) {
    rows.push(['Filters Applied:']);
    for (const [key, value] of Object.entries(options.filters)) {
      if (value !== undefined && value !== '') {
        rows.push([`  ${key}:`, String(value)]);
      }
    }
    rows.push([]);
  }

  // Timestamp
  rows.push(['Generated:', now.toISOString()]);
  rows.push(['Generated By:', options.generatedBy]);
  rows.push([]);

  // KPI summary
  if (options.kpis && options.kpis.length > 0) {
    rows.push(['KPI Summary']);
    rows.push(['Metric', 'Value']);
    for (const kpi of options.kpis) {
      rows.push([kpi.label, String(kpi.value)]);
    }
  }

  const ws = XLSX.utils.aoa_to_sheet(rows);

  // Column widths — first column 22, second column 60
  ws['!cols'] = [{ wch: 22 }, { wch: 60 }];

  // Bold the brand row (row 0)
  const brandCell = ws['A1'];
  if (brandCell) {
    brandCell.s = { font: { bold: true, sz: 16 } };
  }

  // Bold label cells in column A (rows 3, 5+, etc.)
  for (const [addr, cell] of Object.entries(ws)) {
    if (addr.match(/^A\d+$/) && cell && typeof cell.v === 'string') {
      const label = cell.v as string;
      if (
        label === companyName ||
        label.startsWith('Report:') ||
        label.startsWith('Description:') ||
        label.startsWith('Plant') ||
        label.startsWith('Filters') ||
        label === 'Generated:' ||
        label === 'Generated By:' ||
        label === 'KPI Summary' ||
        label === 'Metric'
      ) {
        cell.s = { font: { bold: true } };
      }
    }
  }

  XLSX.utils.book_append_sheet(wb, ws, 'Summary');
  return wb;
}

// ============================================================================
// CORE — addDataSheet
// ============================================================================

/**
 * Add a data sheet to the workbook.
 *
 * - Creates formatted header row from column definitions
 * - Populates rows using column.key to extract values from each row object
 * - Applies number format hints via cell `.z` / `.t` properties
 * - Sets column widths
 * - Optionally freezes header row & adds auto-filter
 * - Optionally stripes alternating rows
 */
export function addDataSheet(
  workbook: XLSX.WorkBook,
  sheetName: string,
  columns: ReportColumn[],
  rows: Record<string, unknown>[],
  options: AddDataSheetOptions = {},
): void {
  const {
    freezeHeader = true,
    freezeColumns = 0,
    autoFilter = true,
    stripeRows = true,
    defaultWidth = 15,
  } = options;

  // Build AOA: header row + data rows
  const aoa: unknown[][] = [];

  // Header row
  aoa.push(columns.map((c) => c.header));

  // Data rows
  for (const row of rows) {
    const dataRow: unknown[] = [];
    for (const col of columns) {
      const raw = row[col.key];
      const formatted = applyCellFormat(raw, col.format);
      dataRow.push(formatted);
    }
    aoa.push(dataRow);
  }

  const ws = XLSX.utils.aoa_to_sheet(aoa);

  // Column widths
  ws['!cols'] = columns.map((c) => ({ wch: c.width || defaultWidth }));

  // Freeze pane — freeze header row (row index 1) + optional left columns
  if (freezeHeader) {
    // XLSX freeze is 0-based: { $freeze$: { x: colCount, y: rowIndex } }
    ws['!freeze'] = { x: freezeColumns, y: 1 };
  }

  // Auto-filter on the header row
  if (autoFilter && columns.length > 0) {
    const range = XLSX.utils.encode_range({
      s: { r: 0, c: 0 },
      e: { r: aoa.length - 1, c: columns.length - 1 },
    });
    ws['!autofilter'] = { ref: range };
  }

  // Apply cell-level styles (numbers, dates, stripe colouring)
  for (let r = 0; r < aoa.length; r++) {
    for (let c = 0; c < columns.length; c++) {
      const cellRef = XLSX.utils.encode_cell({ r, c });
      const cell = ws[cellRef];
      if (!cell) continue;

      const col = columns[c];

      // Number format z-string for Excel
      if (col.format === 'currency') {
        cell.z = '#,##0.00';
        if (typeof cell.v === 'string') {
          const num = Number(cell.v);
          if (!isNaN(num)) { cell.v = num; cell.t = 'n'; }
        }
      } else if (col.format === 'number') {
        cell.z = '#,##0.00';
        if (typeof cell.v === 'string') {
          const num = Number(cell.v);
          if (!isNaN(num)) { cell.v = num; cell.t = 'n'; }
        }
      } else if (col.format === 'percentage') {
        cell.z = '0.0%';
        if (typeof cell.v === 'string') {
          const stripped = (cell.v as string).replace('%', '');
          const num = Number(stripped) / 100;
          if (!isNaN(num)) { cell.v = num; cell.t = 'n'; }
        }
      } else if (col.format === 'date') {
        cell.z = 'yyyy-mm-dd';
      } else if (col.format === 'datetime') {
        cell.z = 'yyyy-mm-dd hh:mm:ss';
      }

      // Header row styling
      if (r === 0) {
        cell.s = {
          font: { bold: true, color: { rgb: 'FFFFFF' } },
          fill: { fgColor: { rgb: '2F5496' } },
          alignment: { horizontal: 'center' },
        };
      } else if (stripeRows && r % 2 === 0) {
        // Alternating row stripe
        cell.s = { fill: { fgColor: { rgb: 'F2F2F2' } } };
      }
    }
  }

  XLSX.utils.book_append_sheet(workbook, ws, sheetName);
}

// ============================================================================
// CORE — addAnalyticsSheet
// ============================================================================

/**
 * Add an analytics / supplementary sheet.
 *
 * Accepts an array of row objects where keys become column headers
 * in the first row. Useful for trend data, Pareto tables, KPI
 * breakdowns, etc.
 */
export function addAnalyticsSheet(
  workbook: XLSX.WorkBook,
  sheetName: string,
  rows: AnalyticsRow[],
  options: AddAnalyticsOptions = {},
): void {
  const { autoFilter = true } = options;

  if (rows.length === 0) {
    // Create an empty sheet with a placeholder
    const ws = XLSX.utils.aoa_to_sheet([['No analytics data available']]);
    XLSX.utils.book_append_sheet(workbook, ws, sheetName);
    return;
  }

  // Determine headers from the first row's keys
  const headers = Object.keys(rows[0]);

  // Build AOA
  const aoa: unknown[][] = [headers];
  for (const row of rows) {
    aoa.push(headers.map((h) => row[h] ?? ''));
  }

  const ws = XLSX.utils.aoa_to_sheet(aoa);

  // Column widths
  ws['!cols'] = headers.map((h) => ({ wch: Math.max(h.length + 4, 15) }));

  // Auto-filter
  if (autoFilter && headers.length > 0) {
    const range = XLSX.utils.encode_range({
      s: { r: 0, c: 0 },
      e: { r: aoa.length - 1, c: headers.length - 1 },
    });
    ws['!autofilter'] = { ref: range };
  }

  // Header styling
  for (let c = 0; c < headers.length; c++) {
    const cellRef = XLSX.utils.encode_cell({ r: 0, c });
    const cell = ws[cellRef];
    if (cell) {
      cell.s = {
        font: { bold: true, color: { rgb: 'FFFFFF' } },
        fill: { fgColor: { rgb: '548235' } },
        alignment: { horizontal: 'center' },
      };
    }
  }

  XLSX.utils.book_append_sheet(workbook, ws, sheetName);
}

// ============================================================================
// EXPORT — generateXlsxBuffer
// ============================================================================

/**
 * Write the workbook to a Buffer suitable for NextResponse.
 */
export function generateXlsxBuffer(workbook: XLSX.WorkBook): Buffer {
  const buffer = XLSX.write(workbook, {
    type: 'buffer',
    bookType: 'xlsx',
    cellStyles: true,
  });
  return Buffer.from(buffer);
}

// ============================================================================
// INTERNAL HELPERS
// ============================================================================

/** Apply column-level format to a raw value for the AOA grid. */
function applyCellFormat(
  raw: unknown,
  format?: ReportColumn['format'],
): string | number {
  switch (format) {
    case 'date':
      return formatDate(raw);
    case 'datetime':
      if (raw == null || raw === '') return '';
      const d = raw instanceof Date ? raw : new Date(String(raw));
      if (isNaN(d.getTime())) return String(raw);
      return XLSX.SSF.format('yyyy-mm-dd hh:mm:ss', d);
    case 'number':
      return formatNumber(raw);
    case 'currency':
      return formatCurrency(raw);
    case 'percentage':
      return formatPercentage(raw);
    case 'text':
    default:
      if (raw == null) return '';
      return String(raw);
  }
}

// ============================================================================
// SAFE FILENAME HELPER
// ============================================================================

/**
 * Convert a report name into a safe filename component.
 */
export function safeFilename(reportName: string): string {
  return reportName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/(^_|_$)/g, '');
}

/**
 * Build a full filename with date stamp.
 */
export function buildFilename(reportName: string, ext: string = 'xlsx'): string {
  const date = new Date().toISOString().split('T')[0];
  return `${safeFilename(reportName)}_${date}.${ext}`;
}
