apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: iassetspro
  labels:
    app.kubernetes.io/name: iassetspro-app
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: iassetspro-eam
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: iassetspro-app
