import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { getSession } from '@/lib/auth';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = getSession(request);
    if (!session) {
      return NextResponse.json({ success: false, error: 'Not authenticated' }, { status: 401 });
    }

    const { id } = await params;

    // Verify work order exists
    const wo = await db.workOrder.findUnique({
      where: { id },
      include: {
        pmSchedule: {
          include: {
            template: {
              include: {
                tasks: {
                  where: { isActive: true },
                  orderBy: { taskNumber: 'asc' },
                },
              },
            },
          },
        },
      },
    });

    if (!wo) {
      return NextResponse.json({ success: false, error: 'Work order not found' }, { status: 404 });
    }

    // Check if task executions already exist for this WO
    const existingTasks = await db.workOrderTaskExecution.findMany({
      where: { workOrderId: id },
      orderBy: { taskNumber: 'asc' },
      include: {
        completedBy: { select: { id: true, fullName: true, username: true } },
      },
    });

    // Auto-generate tasks from template if none exist yet and template has tasks
    if (existingTasks.length === 0 && wo.pmSchedule?.template?.tasks && wo.pmSchedule.template.tasks.length > 0) {
      const templateTasks = wo.pmSchedule.template.tasks;

      // Bulk create task executions from template
      const createData = templateTasks.map((tt) => ({
        workOrderId: id,
        templateTaskId: tt.id,
        taskNumber: tt.taskNumber,
        description: tt.description,
        taskType: tt.taskType,
        requiredParts: tt.requiredParts,
        estimatedMinutes: tt.estimatedMinutes,
        status: 'pending' as const,
      }));

      await db.workOrderTaskExecution.createMany({ data: createData });

      // Re-fetch the newly created tasks
      const tasks = await db.workOrderTaskExecution.findMany({
        where: { workOrderId: id },
        orderBy: { taskNumber: 'asc' },
        include: {
          completedBy: { select: { id: true, fullName: true, username: true } },
        },
      });

      return NextResponse.json({
        success: true,
        data: tasks,
        meta: { source: 'template', templateTitle: wo.pmSchedule.template.title, autoGenerated: true },
      });
    }

    return NextResponse.json({
      success: true,
      data: existingTasks,
      meta: existingTasks.length > 0 ? { source: 'existing' } : { source: 'none' },
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Failed to fetch task checklist';
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = getSession(request);
    if (!session) {
      return NextResponse.json({ success: false, error: 'Not authenticated' }, { status: 401 });
    }

    const { id } = await params;
    const body = await request.json();
    const { description, taskType, requiredParts, estimatedMinutes, taskNumber } = body;

    if (!description || typeof description !== 'string' || description.trim().length === 0) {
      return NextResponse.json({ success: false, error: 'Task description is required' }, { status: 400 });
    }

    // Verify work order exists
    const wo = await db.workOrder.findUnique({ where: { id } });
    if (!wo) {
      return NextResponse.json({ success: false, error: 'Work order not found' }, { status: 404 });
    }

    // Determine next task number if not provided
    let nextTaskNumber = taskNumber;
    if (!nextTaskNumber) {
      const lastTask = await db.workOrderTaskExecution.findFirst({
        where: { workOrderId: id },
        orderBy: { taskNumber: 'desc' },
      });
      nextTaskNumber = (lastTask?.taskNumber ?? 0) + 1;
    }

    // Validate taskType
    const validTaskTypes = ['check', 'measure', 'inspect', 'lubricate', 'replace', 'record'];
    const finalTaskType = taskType && validTaskTypes.includes(taskType) ? taskType : 'check';

    const task = await db.workOrderTaskExecution.create({
      data: {
        workOrderId: id,
        taskNumber: nextTaskNumber,
        description: description.trim(),
        taskType: finalTaskType,
        requiredParts: requiredParts ? JSON.stringify(requiredParts) : null,
        estimatedMinutes: estimatedMinutes ? parseInt(String(estimatedMinutes), 10) : null,
        status: 'pending',
      },
      include: {
        completedBy: { select: { id: true, fullName: true, username: true } },
      },
    });

    // Audit log
    await db.auditLog.create({
      data: {
        userId: session.userId,
        action: 'create',
        entityType: 'wo_task_execution',
        entityId: task.id,
        newValues: JSON.stringify({
          workOrderId: id,
          taskNumber: nextTaskNumber,
          description: description.trim(),
          taskType: finalTaskType,
        }),
      },
    });

    return NextResponse.json({ success: true, data: task }, { status: 201 });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Failed to create task';
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}
