
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('@prisma/client/runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  level: 'level',
  isSystem: 'isSystem',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PermissionScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  module: 'module',
  action: 'action',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RolePermissionScalarFieldEnum = {
  id: 'id',
  roleId: 'roleId',
  permissionId: 'permissionId',
  createdAt: 'createdAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  passwordHash: 'passwordHash',
  fullName: 'fullName',
  staffId: 'staffId',
  phone: 'phone',
  avatar: 'avatar',
  department: 'department',
  status: 'status',
  isVendorAdmin: 'isVendorAdmin',
  resetToken: 'resetToken',
  resetTokenExpires: 'resetTokenExpires',
  notificationPreferences: 'notificationPreferences',
  preferences: 'preferences',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  primaryTrade: 'primaryTrade'
};

exports.Prisma.UserRoleScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  roleId: 'roleId',
  createdAt: 'createdAt'
};

exports.Prisma.UserPermissionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  permissionId: 'permissionId',
  isGranted: 'isGranted',
  expiresAt: 'expiresAt',
  grantedBy: 'grantedBy',
  createdAt: 'createdAt'
};

exports.Prisma.SystemModuleScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  description: 'description',
  version: 'version',
  isCore: 'isCore',
  isSystemLicensed: 'isSystemLicensed',
  licenseKey: 'licenseKey',
  validFrom: 'validFrom',
  validUntil: 'validUntil',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CompanyModuleScalarFieldEnum = {
  id: 'id',
  systemModuleId: 'systemModuleId',
  companyId: 'companyId',
  isActive: 'isActive',
  isEnabled: 'isEnabled',
  licensedAt: 'licensedAt',
  licensedBy: 'licensedBy',
  activatedAt: 'activatedAt',
  activatedBy: 'activatedBy',
  activationLocked: 'activationLocked',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlantScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  location: 'location',
  country: 'country',
  city: 'city',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DepartmentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  plantId: 'plantId',
  parentId: 'parentId',
  supervisorId: 'supervisorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserPlantScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  plantId: 'plantId',
  accessLevel: 'accessLevel',
  isPrimary: 'isPrimary',
  createdAt: 'createdAt'
};

exports.Prisma.MaintenanceRequestScalarFieldEnum = {
  id: 'id',
  requestNumber: 'requestNumber',
  title: 'title',
  description: 'description',
  priority: 'priority',
  category: 'category',
  status: 'status',
  workflowStatus: 'workflowStatus',
  machineDownStatus: 'machineDownStatus',
  assetId: 'assetId',
  departmentId: 'departmentId',
  requestedBy: 'requestedBy',
  supervisorId: 'supervisorId',
  approvedBy: 'approvedBy',
  assignedPlannerId: 'assignedPlannerId',
  workOrderId: 'workOrderId',
  plantId: 'plantId',
  plannedStart: 'plannedStart',
  plannedEnd: 'plannedEnd',
  estimatedHours: 'estimatedHours',
  slaHours: 'slaHours',
  escalationLevel: 'escalationLevel',
  lastEscalatedAt: 'lastEscalatedAt',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkOrderScalarFieldEnum = {
  id: 'id',
  woNumber: 'woNumber',
  title: 'title',
  description: 'description',
  type: 'type',
  priority: 'priority',
  status: 'status',
  maintenanceRequestId: 'maintenanceRequestId',
  pmScheduleId: 'pmScheduleId',
  assetId: 'assetId',
  assetName: 'assetName',
  departmentId: 'departmentId',
  assignedTo: 'assignedTo',
  teamLeaderId: 'teamLeaderId',
  assignedSupervisorId: 'assignedSupervisorId',
  assignedBy: 'assignedBy',
  assignmentType: 'assignmentType',
  plannerId: 'plannerId',
  estimatedHours: 'estimatedHours',
  actualHours: 'actualHours',
  plannedStart: 'plannedStart',
  plannedEnd: 'plannedEnd',
  actualStart: 'actualStart',
  actualEnd: 'actualEnd',
  totalCost: 'totalCost',
  laborCost: 'laborCost',
  partsCost: 'partsCost',
  contractorCost: 'contractorCost',
  failureDescription: 'failureDescription',
  causeDescription: 'causeDescription',
  actionDescription: 'actionDescription',
  tradeActivity: 'tradeActivity',
  safetyNotes: 'safetyNotes',
  ppeRequired: 'ppeRequired',
  plantId: 'plantId',
  notes: 'notes',
  personalTools: 'personalTools',
  isLocked: 'isLocked',
  lockedBy: 'lockedBy',
  lockedAt: 'lockedAt',
  lockReason: 'lockReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  escalationLevel: 'escalationLevel',
  lastEscalatedAt: 'lastEscalatedAt'
};

exports.Prisma.WorkOrderTeamMemberScalarFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  userId: 'userId',
  role: 'role',
  accessLevel: 'accessLevel',
  assignedAt: 'assignedAt'
};

exports.Prisma.WorkOrderTimeLogScalarFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  userId: 'userId',
  action: 'action',
  duration: 'duration',
  notes: 'notes',
  timestamp: 'timestamp'
};

exports.Prisma.WorkOrderMaterialScalarFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  itemId: 'itemId',
  itemName: 'itemName',
  quantity: 'quantity',
  unitCost: 'unitCost',
  totalCost: 'totalCost',
  status: 'status',
  requestedBy: 'requestedBy',
  approvedBy: 'approvedBy',
  issuedBy: 'issuedBy',
  createdAt: 'createdAt'
};

exports.Prisma.WorkOrderCommentScalarFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  userId: 'userId',
  content: 'content',
  createdAt: 'createdAt'
};

exports.Prisma.StatusTransitionScalarFieldEnum = {
  id: 'id',
  entityType: 'entityType',
  fromStatus: 'fromStatus',
  toStatus: 'toStatus',
  allowedRoleSlugs: 'allowedRoleSlugs',
  requiresApproval: 'requiresApproval',
  requiresReason: 'requiresReason',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  action: 'action',
  entityType: 'entityType',
  entityId: 'entityId',
  oldValues: 'oldValues',
  newValues: 'newValues',
  ipAddress: 'ipAddress',
  createdAt: 'createdAt'
};

exports.Prisma.EscalationLogScalarFieldEnum = {
  id: 'id',
  entityType: 'entityType',
  entityId: 'entityId',
  level: 'level',
  reason: 'reason',
  notifiedUsers: 'notifiedUsers',
  createdAt: 'createdAt'
};

exports.Prisma.CompanyProfileScalarFieldEnum = {
  id: 'id',
  companyName: 'companyName',
  tradingName: 'tradingName',
  logo: 'logo',
  address: 'address',
  city: 'city',
  region: 'region',
  country: 'country',
  postalCode: 'postalCode',
  phone: 'phone',
  email: 'email',
  website: 'website',
  industry: 'industry',
  employeeCount: 'employeeCount',
  fiscalYearStart: 'fiscalYearStart',
  timezone: 'timezone',
  currency: 'currency',
  dateFormat: 'dateFormat',
  isSetupComplete: 'isSetupComplete',
  setupCompletedAt: 'setupCompletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  message: 'message',
  entityType: 'entityType',
  entityId: 'entityId',
  actionUrl: 'actionUrl',
  isRead: 'isRead',
  createdAt: 'createdAt'
};

exports.Prisma.AssetCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  description: 'description',
  parentId: 'parentId',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AssetScalarFieldEnum = {
  id: 'id',
  name: 'name',
  assetTag: 'assetTag',
  description: 'description',
  categoryId: 'categoryId',
  serialNumber: 'serialNumber',
  manufacturer: 'manufacturer',
  model: 'model',
  yearManufactured: 'yearManufactured',
  condition: 'condition',
  status: 'status',
  criticality: 'criticality',
  location: 'location',
  building: 'building',
  floor: 'floor',
  area: 'area',
  plantId: 'plantId',
  departmentId: 'departmentId',
  purchaseDate: 'purchaseDate',
  purchaseCost: 'purchaseCost',
  warrantyExpiry: 'warrantyExpiry',
  installedDate: 'installedDate',
  expectedLifeYears: 'expectedLifeYears',
  currentValue: 'currentValue',
  depreciationRate: 'depreciationRate',
  imageUrl: 'imageUrl',
  drawingsUrl: 'drawingsUrl',
  manualUrl: 'manualUrl',
  specification: 'specification',
  parentId: 'parentId',
  isActive: 'isActive',
  createdById: 'createdById',
  assignedToId: 'assignedToId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InventoryItemScalarFieldEnum = {
  id: 'id',
  itemCode: 'itemCode',
  name: 'name',
  description: 'description',
  category: 'category',
  unitOfMeasure: 'unitOfMeasure',
  currentStock: 'currentStock',
  minStockLevel: 'minStockLevel',
  maxStockLevel: 'maxStockLevel',
  reorderQuantity: 'reorderQuantity',
  unitCost: 'unitCost',
  supplier: 'supplier',
  supplierPartNumber: 'supplierPartNumber',
  location: 'location',
  binLocation: 'binLocation',
  shelfLocation: 'shelfLocation',
  plantId: 'plantId',
  locationId: 'locationId',
  supplierId: 'supplierId',
  isActive: 'isActive',
  specification: 'specification',
  imageUrls: 'imageUrls',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StockMovementScalarFieldEnum = {
  id: 'id',
  itemId: 'itemId',
  type: 'type',
  quantity: 'quantity',
  previousStock: 'previousStock',
  newStock: 'newStock',
  reason: 'reason',
  referenceType: 'referenceType',
  referenceId: 'referenceId',
  performedById: 'performedById',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.PmScheduleScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  assetId: 'assetId',
  frequencyType: 'frequencyType',
  frequencyValue: 'frequencyValue',
  lastCompletedDate: 'lastCompletedDate',
  nextDueDate: 'nextDueDate',
  estimatedDuration: 'estimatedDuration',
  priority: 'priority',
  assignedToId: 'assignedToId',
  departmentId: 'departmentId',
  isActive: 'isActive',
  autoGenerateWO: 'autoGenerateWO',
  leadDays: 'leadDays',
  woTypeId: 'woTypeId',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  templateId: 'templateId'
};

exports.Prisma.PmTemplateScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  type: 'type',
  category: 'category',
  estimatedDuration: 'estimatedDuration',
  priority: 'priority',
  requiredSkills: 'requiredSkills',
  requiredTools: 'requiredTools',
  isActive: 'isActive',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PmTemplateTaskScalarFieldEnum = {
  id: 'id',
  templateId: 'templateId',
  taskNumber: 'taskNumber',
  description: 'description',
  taskType: 'taskType',
  requiredParts: 'requiredParts',
  estimatedMinutes: 'estimatedMinutes',
  sortOrder: 'sortOrder',
  isActive: 'isActive'
};

exports.Prisma.PmTriggerScalarFieldEnum = {
  id: 'id',
  scheduleId: 'scheduleId',
  triggerType: 'triggerType',
  triggerValue: 'triggerValue',
  triggerConfig: 'triggerConfig',
  lastTriggeredAt: 'lastTriggeredAt',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkOrderStatusHistoryScalarFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  fromStatus: 'fromStatus',
  toStatus: 'toStatus',
  performedById: 'performedById',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.MaintenanceRequestCommentScalarFieldEnum = {
  id: 'id',
  maintenanceRequestId: 'maintenanceRequestId',
  userId: 'userId',
  content: 'content',
  createdAt: 'createdAt'
};

exports.Prisma.TradeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  category: 'category',
  description: 'description',
  color: 'color',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserSkillScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tradeId: 'tradeId',
  proficiencyLevel: 'proficiencyLevel',
  yearsExperience: 'yearsExperience',
  certified: 'certified',
  createdAt: 'createdAt'
};

exports.Prisma.IotDeviceScalarFieldEnum = {
  id: 'id',
  name: 'name',
  deviceCode: 'deviceCode',
  type: 'type',
  protocol: 'protocol',
  status: 'status',
  location: 'location',
  plantId: 'plantId',
  assetId: 'assetId',
  groupId: 'groupId',
  parameter: 'parameter',
  unit: 'unit',
  thresholdMin: 'thresholdMin',
  thresholdMax: 'thresholdMax',
  lastReading: 'lastReading',
  lastSeen: 'lastSeen',
  batteryLevel: 'batteryLevel',
  signalStrength: 'signalStrength',
  firmwareVersion: 'firmwareVersion',
  pollingInterval: 'pollingInterval',
  description: 'description',
  isActive: 'isActive',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.IotReadingScalarFieldEnum = {
  id: 'id',
  deviceId: 'deviceId',
  value: 'value',
  unit: 'unit',
  timestamp: 'timestamp',
  isAnomaly: 'isAnomaly'
};

exports.Prisma.IotAlertScalarFieldEnum = {
  id: 'id',
  deviceId: 'deviceId',
  ruleId: 'ruleId',
  severity: 'severity',
  message: 'message',
  value: 'value',
  threshold: 'threshold',
  status: 'status',
  acknowledgedBy: 'acknowledgedBy',
  acknowledgedAt: 'acknowledgedAt',
  resolvedAt: 'resolvedAt',
  createdAt: 'createdAt'
};

exports.Prisma.IotAlertRuleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  deviceId: 'deviceId',
  parameter: 'parameter',
  operator: 'operator',
  threshold: 'threshold',
  severity: 'severity',
  cooldownMinutes: 'cooldownMinutes',
  isActive: 'isActive',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ToolScalarFieldEnum = {
  id: 'id',
  toolCode: 'toolCode',
  name: 'name',
  description: 'description',
  category: 'category',
  serialNumber: 'serialNumber',
  status: 'status',
  condition: 'condition',
  location: 'location',
  plantId: 'plantId',
  purchaseDate: 'purchaseDate',
  purchaseCost: 'purchaseCost',
  currentValue: 'currentValue',
  manufacturer: 'manufacturer',
  model: 'model',
  assignedToId: 'assignedToId',
  checkedOutAt: 'checkedOutAt',
  expectedReturn: 'expectedReturn',
  isActive: 'isActive',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ToolTransactionScalarFieldEnum = {
  id: 'id',
  toolId: 'toolId',
  type: 'type',
  fromUserId: 'fromUserId',
  toUserId: 'toUserId',
  notes: 'notes',
  performedById: 'performedById',
  createdAt: 'createdAt'
};

exports.Prisma.InventoryLocationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  type: 'type',
  address: 'address',
  isActive: 'isActive',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InventoryAdjustmentScalarFieldEnum = {
  id: 'id',
  adjustmentNumber: 'adjustmentNumber',
  itemId: 'itemId',
  type: 'type',
  quantity: 'quantity',
  reason: 'reason',
  status: 'status',
  approvedById: 'approvedById',
  approvedAt: 'approvedAt',
  notes: 'notes',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InventoryRequestScalarFieldEnum = {
  id: 'id',
  requestNumber: 'requestNumber',
  title: 'title',
  description: 'description',
  status: 'status',
  priority: 'priority',
  requestedById: 'requestedById',
  departmentId: 'departmentId',
  plantId: 'plantId',
  approvedById: 'approvedById',
  approvedAt: 'approvedAt',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InventoryRequestItemScalarFieldEnum = {
  id: 'id',
  requestId: 'requestId',
  itemId: 'itemId',
  quantityRequested: 'quantityRequested',
  quantityFulfilled: 'quantityFulfilled',
  unitCost: 'unitCost',
  notes: 'notes'
};

exports.Prisma.InventoryTransferScalarFieldEnum = {
  id: 'id',
  transferNumber: 'transferNumber',
  itemId: 'itemId',
  fromLocationId: 'fromLocationId',
  toLocationId: 'toLocationId',
  quantity: 'quantity',
  status: 'status',
  requestedById: 'requestedById',
  approvedById: 'approvedById',
  approvedAt: 'approvedAt',
  completedAt: 'completedAt',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SupplierScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  contactPerson: 'contactPerson',
  email: 'email',
  phone: 'phone',
  address: 'address',
  city: 'city',
  country: 'country',
  website: 'website',
  rating: 'rating',
  isActive: 'isActive',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PurchaseOrderScalarFieldEnum = {
  id: 'id',
  poNumber: 'poNumber',
  supplierId: 'supplierId',
  status: 'status',
  priority: 'priority',
  expectedDelivery: 'expectedDelivery',
  notes: 'notes',
  totalAmount: 'totalAmount',
  createdById: 'createdById',
  approvedById: 'approvedById',
  approvedAt: 'approvedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PurchaseOrderItemScalarFieldEnum = {
  id: 'id',
  poId: 'poId',
  itemId: 'itemId',
  quantity: 'quantity',
  unitCost: 'unitCost',
  totalCost: 'totalCost',
  quantityReceived: 'quantityReceived',
  description: 'description'
};

exports.Prisma.ReceivingRecordScalarFieldEnum = {
  id: 'id',
  poId: 'poId',
  itemId: 'itemId',
  quantityReceived: 'quantityReceived',
  condition: 'condition',
  receivedById: 'receivedById',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.SafetyIncidentScalarFieldEnum = {
  id: 'id',
  incidentNumber: 'incidentNumber',
  title: 'title',
  description: 'description',
  type: 'type',
  severity: 'severity',
  status: 'status',
  incidentDate: 'incidentDate',
  location: 'location',
  assetId: 'assetId',
  departmentId: 'departmentId',
  plantId: 'plantId',
  reportedById: 'reportedById',
  investigatedById: 'investigatedById',
  rootCause: 'rootCause',
  correctiveAction: 'correctiveAction',
  daysLost: 'daysLost',
  cost: 'cost',
  notes: 'notes',
  escalationLevel: 'escalationLevel',
  lastEscalatedAt: 'lastEscalatedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SafetyInspectionScalarFieldEnum = {
  id: 'id',
  inspectionNumber: 'inspectionNumber',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  scheduledDate: 'scheduledDate',
  completedDate: 'completedDate',
  location: 'location',
  departmentId: 'departmentId',
  inspectorId: 'inspectorId',
  findings: 'findings',
  score: 'score',
  maxScore: 'maxScore',
  notes: 'notes',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SafetyTrainingScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  trainer: 'trainer',
  scheduledDate: 'scheduledDate',
  completedDate: 'completedDate',
  location: 'location',
  attendees: 'attendees',
  durationHours: 'durationHours',
  notes: 'notes',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SafetyEquipmentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  type: 'type',
  status: 'status',
  location: 'location',
  quantity: 'quantity',
  expiryDate: 'expiryDate',
  lastInspected: 'lastInspected',
  nextInspection: 'nextInspection',
  condition: 'condition',
  notes: 'notes',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SafetyPermitScalarFieldEnum = {
  id: 'id',
  permitNumber: 'permitNumber',
  title: 'title',
  type: 'type',
  status: 'status',
  description: 'description',
  location: 'location',
  startDate: 'startDate',
  endDate: 'endDate',
  requestedById: 'requestedById',
  approvedById: 'approvedById',
  approvedAt: 'approvedAt',
  hazardAssessment: 'hazardAssessment',
  precautions: 'precautions',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.QualityInspectionScalarFieldEnum = {
  id: 'id',
  inspectionNumber: 'inspectionNumber',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  orderId: 'orderId',
  assetId: 'assetId',
  itemId: 'itemId',
  plantId: 'plantId',
  inspectedById: 'inspectedById',
  scheduledDate: 'scheduledDate',
  completedDate: 'completedDate',
  result: 'result',
  defects: 'defects',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NonConformanceReportScalarFieldEnum = {
  id: 'id',
  ncrNumber: 'ncrNumber',
  title: 'title',
  description: 'description',
  severity: 'severity',
  status: 'status',
  type: 'type',
  sourceInspectionId: 'sourceInspectionId',
  assetId: 'assetId',
  itemId: 'itemId',
  departmentId: 'departmentId',
  raisedById: 'raisedById',
  rootCause: 'rootCause',
  correctiveAction: 'correctiveAction',
  dueDate: 'dueDate',
  completedDate: 'completedDate',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.QualityAuditScalarFieldEnum = {
  id: 'id',
  auditNumber: 'auditNumber',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  scheduledDate: 'scheduledDate',
  completedDate: 'completedDate',
  auditedById: 'auditedById',
  departmentId: 'departmentId',
  scope: 'scope',
  findings: 'findings',
  score: 'score',
  maxScore: 'maxScore',
  recommendation: 'recommendation',
  notes: 'notes',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.QualityControlPlanScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  itemId: 'itemId',
  assetId: 'assetId',
  type: 'type',
  frequency: 'frequency',
  characteristics: 'characteristics',
  sampleSize: 'sampleSize',
  isActive: 'isActive',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CorrectiveActionScalarFieldEnum = {
  id: 'id',
  capaNumber: 'capaNumber',
  title: 'title',
  description: 'description',
  type: 'type',
  source: 'source',
  sourceId: 'sourceId',
  severity: 'severity',
  status: 'status',
  rootCause: 'rootCause',
  correctiveAction: 'correctiveAction',
  preventiveAction: 'preventiveAction',
  responsibleId: 'responsibleId',
  dueDate: 'dueDate',
  verifiedById: 'verifiedById',
  verifiedAt: 'verifiedAt',
  effectiveness: 'effectiveness',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SpcProcessScalarFieldEnum = {
  id: 'id',
  processName: 'processName',
  parameter: 'parameter',
  unit: 'unit',
  specMin: 'specMin',
  specMax: 'specMax',
  target: 'target',
  status: 'status',
  samples: 'samples',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkCenterScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  description: 'description',
  type: 'type',
  status: 'status',
  location: 'location',
  capacity: 'capacity',
  capacityUnit: 'capacityUnit',
  isActive: 'isActive',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductionOrderScalarFieldEnum = {
  id: 'id',
  orderNumber: 'orderNumber',
  title: 'title',
  description: 'description',
  status: 'status',
  priority: 'priority',
  productId: 'productId',
  productName: 'productName',
  quantity: 'quantity',
  completedQty: 'completedQty',
  unitCost: 'unitCost',
  workCenterId: 'workCenterId',
  plantId: 'plantId',
  scheduledStart: 'scheduledStart',
  scheduledEnd: 'scheduledEnd',
  actualStart: 'actualStart',
  actualEnd: 'actualEnd',
  notes: 'notes',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductionBatchScalarFieldEnum = {
  id: 'id',
  batchNumber: 'batchNumber',
  orderId: 'orderId',
  productId: 'productId',
  productName: 'productName',
  quantity: 'quantity',
  completedQty: 'completedQty',
  status: 'status',
  startDate: 'startDate',
  endDate: 'endDate',
  yield_: 'yield_',
  notes: 'notes',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MeterReadingScalarFieldEnum = {
  id: 'id',
  readingNumber: 'readingNumber',
  assetId: 'assetId',
  plantId: 'plantId',
  meterName: 'meterName',
  value: 'value',
  unit: 'unit',
  readingDate: 'readingDate',
  previousValue: 'previousValue',
  consumption: 'consumption',
  notes: 'notes',
  readById: 'readById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TrainingCourseScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  category: 'category',
  type: 'type',
  durationHours: 'durationHours',
  status: 'status',
  instructor: 'instructor',
  maxParticipants: 'maxParticipants',
  certification: 'certification',
  validForMonths: 'validForMonths',
  notes: 'notes',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ShiftHandoverScalarFieldEnum = {
  id: 'id',
  shiftDate: 'shiftDate',
  shiftType: 'shiftType',
  fromShift: 'fromShift',
  toShift: 'toShift',
  departmentId: 'departmentId',
  handedOverById: 'handedOverById',
  receivedById: 'receivedById',
  status: 'status',
  tasksSummary: 'tasksSummary',
  pendingIssues: 'pendingIssues',
  safetyNotes: 'safetyNotes',
  equipmentStatus: 'equipmentStatus',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ChecklistScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  type: 'type',
  frequency: 'frequency',
  departmentId: 'departmentId',
  assetId: 'assetId',
  isActive: 'isActive',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ChecklistItemScalarFieldEnum = {
  id: 'id',
  checklistId: 'checklistId',
  item: 'item',
  description: 'description',
  sortOrder: 'sortOrder',
  isRequired: 'isRequired'
};

exports.Prisma.ChecklistResponseScalarFieldEnum = {
  id: 'id',
  checklistId: 'checklistId',
  completedById: 'completedById',
  status: 'status',
  responses: 'responses',
  notes: 'notes',
  completedAt: 'completedAt'
};

exports.Prisma.SurveyScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  targetGroup: 'targetGroup',
  questions: 'questions',
  responses: 'responses',
  totalResponses: 'totalResponses',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CalibrationRecordScalarFieldEnum = {
  id: 'id',
  calibrationNumber: 'calibrationNumber',
  title: 'title',
  description: 'description',
  assetId: 'assetId',
  instrumentName: 'instrumentName',
  serialNumber: 'serialNumber',
  calibrationDate: 'calibrationDate',
  nextDueDate: 'nextDueDate',
  status: 'status',
  standardUsed: 'standardUsed',
  result: 'result',
  asFound: 'asFound',
  asLeft: 'asLeft',
  uncertainty: 'uncertainty',
  performedById: 'performedById',
  approvedById: 'approvedById',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RiskAssessmentScalarFieldEnum = {
  id: 'id',
  assessmentNumber: 'assessmentNumber',
  title: 'title',
  description: 'description',
  assetId: 'assetId',
  departmentId: 'departmentId',
  assessmentDate: 'assessmentDate',
  nextReview: 'nextReview',
  status: 'status',
  likelihood: 'likelihood',
  consequence: 'consequence',
  riskLevel: 'riskLevel',
  hazards: 'hazards',
  controls: 'controls',
  residualRisk: 'residualRisk',
  assessorId: 'assessorId',
  reviewerId: 'reviewerId',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LotoRecordScalarFieldEnum = {
  id: 'id',
  lotoNumber: 'lotoNumber',
  title: 'title',
  description: 'description',
  assetId: 'assetId',
  departmentId: 'departmentId',
  plantId: 'plantId',
  workOrderId: 'workOrderId',
  lotoType: 'lotoType',
  energySource: 'energySource',
  energySourceDesc: 'energySourceDesc',
  requestedById: 'requestedById',
  requestDate: 'requestDate',
  scheduledDate: 'scheduledDate',
  requiredFromDate: 'requiredFromDate',
  requiredToDate: 'requiredToDate',
  supervisorId: 'supervisorId',
  supervisorApprovedAt: 'supervisorApprovedAt',
  safetyOfficerId: 'safetyOfficerId',
  safetyOfficerApprovedAt: 'safetyOfficerApprovedAt',
  status: 'status',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  cancelledAt: 'cancelledAt',
  cancelledReason: 'cancelledReason',
  isolationPoints: 'isolationPoints',
  lockDevices: 'lockDevices',
  tagNumbers: 'tagNumbers',
  verifiedBy: 'verifiedBy',
  verificationDate: 'verificationDate',
  affectedWorkers: 'affectedWorkers',
  workerCount: 'workerCount',
  appliedBy: 'appliedBy',
  removedBy: 'removedBy',
  removedAt: 'removedAt',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BillOfMaterialScalarFieldEnum = {
  id: 'id',
  parentId: 'parentId',
  childAssetId: 'childAssetId',
  partNumber: 'partNumber',
  quantity: 'quantity',
  unit: 'unit',
  specification: 'specification',
  status: 'status',
  revision: 'revision',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.DigitalTwinScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  name: 'name',
  description: 'description',
  type: 'type',
  parameters: 'parameters',
  connections: 'connections',
  specification: 'specification',
  healthScore: 'healthScore',
  syncInterval: 'syncInterval',
  lastSynced: 'lastSynced',
  isActive: 'isActive',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ConversationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ConversationParticipantScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  convoId: 'convoId',
  joinedAt: 'joinedAt',
  lastReadAt: 'lastReadAt'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  token: 'token',
  userId: 'userId',
  roles: 'roles',
  permissions: 'permissions',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  lastSeen: 'lastSeen'
};

exports.Prisma.ChatMessageScalarFieldEnum = {
  id: 'id',
  convoId: 'convoId',
  senderId: 'senderId',
  content: 'content',
  messageType: 'messageType',
  createdAt: 'createdAt'
};

exports.Prisma.RepairMaterialRequestScalarFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  itemId: 'itemId',
  itemName: 'itemName',
  quantityRequested: 'quantityRequested',
  quantityApproved: 'quantityApproved',
  quantityIssued: 'quantityIssued',
  quantityReturned: 'quantityReturned',
  unit: 'unit',
  unitCost: 'unitCost',
  estimatedCost: 'estimatedCost',
  urgency: 'urgency',
  reason: 'reason',
  notes: 'notes',
  status: 'status',
  supervisorApprovedQuantity: 'supervisorApprovedQuantity',
  storekeeperApprovedQuantity: 'storekeeperApprovedQuantity',
  stockReserved: 'stockReserved',
  requestedById: 'requestedById',
  supervisorApprovedById: 'supervisorApprovedById',
  supervisorApprovedAt: 'supervisorApprovedAt',
  storekeeperApprovedById: 'storekeeperApprovedById',
  storekeeperApprovedAt: 'storekeeperApprovedAt',
  issuedById: 'issuedById',
  issuedAt: 'issuedAt',
  returnedById: 'returnedById',
  returnedAt: 'returnedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RepairToolRequestScalarFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  toolId: 'toolId',
  toolName: 'toolName',
  reason: 'reason',
  notes: 'notes',
  status: 'status',
  urgency: 'urgency',
  rejectionReason: 'rejectionReason',
  toolConditionAtIssue: 'toolConditionAtIssue',
  toolConditionAtReturn: 'toolConditionAtReturn',
  requestedById: 'requestedById',
  supervisorApprovedById: 'supervisorApprovedById',
  supervisorApprovedAt: 'supervisorApprovedAt',
  storekeeperApprovedById: 'storekeeperApprovedById',
  storekeeperApprovedAt: 'storekeeperApprovedAt',
  issuedById: 'issuedById',
  issuedAt: 'issuedAt',
  returnedById: 'returnedById',
  returnedAt: 'returnedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ToolTransferRequestScalarFieldEnum = {
  id: 'id',
  toolId: 'toolId',
  fromUserId: 'fromUserId',
  toUserId: 'toUserId',
  reason: 'reason',
  notes: 'notes',
  status: 'status',
  rejectionReason: 'rejectionReason',
  toolConditionAtTransfer: 'toolConditionAtTransfer',
  fromUserAcceptedAt: 'fromUserAcceptedAt',
  toUserAcceptedAt: 'toUserAcceptedAt',
  requestedById: 'requestedById',
  storekeeperApprovedById: 'storekeeperApprovedById',
  storekeeperApprovedAt: 'storekeeperApprovedAt',
  transferredAt: 'transferredAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkOrderDowntimeScalarFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  assetId: 'assetId',
  assetName: 'assetName',
  downtimeStart: 'downtimeStart',
  downtimeEnd: 'downtimeEnd',
  durationMinutes: 'durationMinutes',
  reason: 'reason',
  category: 'category',
  impactLevel: 'impactLevel',
  productionLoss: 'productionLoss',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RepairCompletionScalarFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  completionNotes: 'completionNotes',
  findings: 'findings',
  rootCause: 'rootCause',
  correctiveAction: 'correctiveAction',
  materialsUsedSummary: 'materialsUsedSummary',
  toolsUsedSummary: 'toolsUsedSummary',
  totalLaborHours: 'totalLaborHours',
  totalMaterialCost: 'totalMaterialCost',
  totalToolCost: 'totalToolCost',
  totalDowntimeMinutes: 'totalDowntimeMinutes',
  supervisorReviewNotes: 'supervisorReviewNotes',
  supervisorApprovedById: 'supervisorApprovedById',
  supervisorApprovedAt: 'supervisorApprovedAt',
  supervisorStatus: 'supervisorStatus',
  reworkReason: 'reworkReason',
  reworkCount: 'reworkCount',
  plannerClosedById: 'plannerClosedById',
  plannerClosedAt: 'plannerClosedAt',
  plannerStatus: 'plannerStatus',
  closureNotes: 'closureNotes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AttachmentScalarFieldEnum = {
  id: 'id',
  fileName: 'fileName',
  fileType: 'fileType',
  fileSize: 'fileSize',
  filePath: 'filePath',
  entityType: 'entityType',
  entityId: 'entityId',
  uploadedById: 'uploadedById',
  uploadedAt: 'uploadedAt',
  description: 'description'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.RoleOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description'
};

exports.Prisma.PermissionOrderByRelevanceFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  module: 'module',
  action: 'action',
  description: 'description'
};

exports.Prisma.RolePermissionOrderByRelevanceFieldEnum = {
  id: 'id',
  roleId: 'roleId',
  permissionId: 'permissionId'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.UserOrderByRelevanceFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  passwordHash: 'passwordHash',
  fullName: 'fullName',
  staffId: 'staffId',
  phone: 'phone',
  avatar: 'avatar',
  department: 'department',
  status: 'status',
  resetToken: 'resetToken',
  primaryTrade: 'primaryTrade'
};

exports.Prisma.UserRoleOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  roleId: 'roleId'
};

exports.Prisma.UserPermissionOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  permissionId: 'permissionId',
  grantedBy: 'grantedBy'
};

exports.Prisma.SystemModuleOrderByRelevanceFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  description: 'description',
  version: 'version',
  licenseKey: 'licenseKey'
};

exports.Prisma.CompanyModuleOrderByRelevanceFieldEnum = {
  id: 'id',
  systemModuleId: 'systemModuleId',
  companyId: 'companyId',
  licensedBy: 'licensedBy',
  activatedBy: 'activatedBy'
};

exports.Prisma.PlantOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  location: 'location',
  country: 'country',
  city: 'city'
};

exports.Prisma.DepartmentOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  plantId: 'plantId',
  parentId: 'parentId',
  supervisorId: 'supervisorId'
};

exports.Prisma.UserPlantOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  plantId: 'plantId',
  accessLevel: 'accessLevel'
};

exports.Prisma.MaintenanceRequestOrderByRelevanceFieldEnum = {
  id: 'id',
  requestNumber: 'requestNumber',
  title: 'title',
  description: 'description',
  priority: 'priority',
  category: 'category',
  status: 'status',
  workflowStatus: 'workflowStatus',
  assetId: 'assetId',
  departmentId: 'departmentId',
  requestedBy: 'requestedBy',
  supervisorId: 'supervisorId',
  approvedBy: 'approvedBy',
  assignedPlannerId: 'assignedPlannerId',
  workOrderId: 'workOrderId',
  plantId: 'plantId',
  notes: 'notes'
};

exports.Prisma.WorkOrderOrderByRelevanceFieldEnum = {
  id: 'id',
  woNumber: 'woNumber',
  title: 'title',
  description: 'description',
  type: 'type',
  priority: 'priority',
  status: 'status',
  maintenanceRequestId: 'maintenanceRequestId',
  pmScheduleId: 'pmScheduleId',
  assetId: 'assetId',
  assetName: 'assetName',
  departmentId: 'departmentId',
  assignedTo: 'assignedTo',
  teamLeaderId: 'teamLeaderId',
  assignedSupervisorId: 'assignedSupervisorId',
  assignedBy: 'assignedBy',
  assignmentType: 'assignmentType',
  plannerId: 'plannerId',
  failureDescription: 'failureDescription',
  causeDescription: 'causeDescription',
  actionDescription: 'actionDescription',
  tradeActivity: 'tradeActivity',
  safetyNotes: 'safetyNotes',
  ppeRequired: 'ppeRequired',
  plantId: 'plantId',
  notes: 'notes',
  personalTools: 'personalTools',
  lockedBy: 'lockedBy',
  lockReason: 'lockReason'
};

exports.Prisma.WorkOrderTeamMemberOrderByRelevanceFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  userId: 'userId',
  role: 'role',
  accessLevel: 'accessLevel'
};

exports.Prisma.WorkOrderTimeLogOrderByRelevanceFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  userId: 'userId',
  action: 'action',
  notes: 'notes'
};

exports.Prisma.WorkOrderMaterialOrderByRelevanceFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  itemId: 'itemId',
  itemName: 'itemName',
  status: 'status',
  requestedBy: 'requestedBy',
  approvedBy: 'approvedBy',
  issuedBy: 'issuedBy'
};

exports.Prisma.WorkOrderCommentOrderByRelevanceFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  userId: 'userId',
  content: 'content'
};

exports.Prisma.StatusTransitionOrderByRelevanceFieldEnum = {
  id: 'id',
  entityType: 'entityType',
  fromStatus: 'fromStatus',
  toStatus: 'toStatus',
  allowedRoleSlugs: 'allowedRoleSlugs'
};

exports.Prisma.AuditLogOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  action: 'action',
  entityType: 'entityType',
  entityId: 'entityId',
  oldValues: 'oldValues',
  newValues: 'newValues',
  ipAddress: 'ipAddress'
};

exports.Prisma.EscalationLogOrderByRelevanceFieldEnum = {
  id: 'id',
  entityType: 'entityType',
  entityId: 'entityId',
  reason: 'reason',
  notifiedUsers: 'notifiedUsers'
};

exports.Prisma.CompanyProfileOrderByRelevanceFieldEnum = {
  id: 'id',
  companyName: 'companyName',
  tradingName: 'tradingName',
  logo: 'logo',
  address: 'address',
  city: 'city',
  region: 'region',
  country: 'country',
  postalCode: 'postalCode',
  phone: 'phone',
  email: 'email',
  website: 'website',
  industry: 'industry',
  employeeCount: 'employeeCount',
  fiscalYearStart: 'fiscalYearStart',
  timezone: 'timezone',
  currency: 'currency',
  dateFormat: 'dateFormat'
};

exports.Prisma.NotificationOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  message: 'message',
  entityType: 'entityType',
  entityId: 'entityId',
  actionUrl: 'actionUrl'
};

exports.Prisma.AssetCategoryOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  description: 'description',
  parentId: 'parentId'
};

exports.Prisma.AssetOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  assetTag: 'assetTag',
  description: 'description',
  categoryId: 'categoryId',
  serialNumber: 'serialNumber',
  manufacturer: 'manufacturer',
  model: 'model',
  condition: 'condition',
  status: 'status',
  criticality: 'criticality',
  location: 'location',
  building: 'building',
  floor: 'floor',
  area: 'area',
  plantId: 'plantId',
  departmentId: 'departmentId',
  imageUrl: 'imageUrl',
  drawingsUrl: 'drawingsUrl',
  manualUrl: 'manualUrl',
  specification: 'specification',
  parentId: 'parentId',
  createdById: 'createdById',
  assignedToId: 'assignedToId'
};

exports.Prisma.InventoryItemOrderByRelevanceFieldEnum = {
  id: 'id',
  itemCode: 'itemCode',
  name: 'name',
  description: 'description',
  category: 'category',
  unitOfMeasure: 'unitOfMeasure',
  supplier: 'supplier',
  supplierPartNumber: 'supplierPartNumber',
  location: 'location',
  binLocation: 'binLocation',
  shelfLocation: 'shelfLocation',
  plantId: 'plantId',
  locationId: 'locationId',
  supplierId: 'supplierId',
  specification: 'specification',
  imageUrls: 'imageUrls',
  createdById: 'createdById'
};

exports.Prisma.StockMovementOrderByRelevanceFieldEnum = {
  id: 'id',
  itemId: 'itemId',
  type: 'type',
  reason: 'reason',
  referenceType: 'referenceType',
  referenceId: 'referenceId',
  performedById: 'performedById',
  notes: 'notes'
};

exports.Prisma.PmScheduleOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  assetId: 'assetId',
  frequencyType: 'frequencyType',
  priority: 'priority',
  assignedToId: 'assignedToId',
  departmentId: 'departmentId',
  woTypeId: 'woTypeId',
  createdById: 'createdById',
  templateId: 'templateId'
};

exports.Prisma.PmTemplateOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  type: 'type',
  category: 'category',
  priority: 'priority',
  requiredSkills: 'requiredSkills',
  requiredTools: 'requiredTools',
  createdById: 'createdById'
};

exports.Prisma.PmTemplateTaskOrderByRelevanceFieldEnum = {
  id: 'id',
  templateId: 'templateId',
  description: 'description',
  taskType: 'taskType',
  requiredParts: 'requiredParts'
};

exports.Prisma.PmTriggerOrderByRelevanceFieldEnum = {
  id: 'id',
  scheduleId: 'scheduleId',
  triggerType: 'triggerType',
  triggerConfig: 'triggerConfig'
};

exports.Prisma.WorkOrderStatusHistoryOrderByRelevanceFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  fromStatus: 'fromStatus',
  toStatus: 'toStatus',
  performedById: 'performedById',
  notes: 'notes'
};

exports.Prisma.MaintenanceRequestCommentOrderByRelevanceFieldEnum = {
  id: 'id',
  maintenanceRequestId: 'maintenanceRequestId',
  userId: 'userId',
  content: 'content'
};

exports.Prisma.TradeOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  category: 'category',
  description: 'description',
  color: 'color'
};

exports.Prisma.UserSkillOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  tradeId: 'tradeId',
  proficiencyLevel: 'proficiencyLevel'
};

exports.Prisma.IotDeviceOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  deviceCode: 'deviceCode',
  type: 'type',
  protocol: 'protocol',
  status: 'status',
  location: 'location',
  plantId: 'plantId',
  assetId: 'assetId',
  groupId: 'groupId',
  parameter: 'parameter',
  unit: 'unit',
  firmwareVersion: 'firmwareVersion',
  description: 'description',
  createdById: 'createdById'
};

exports.Prisma.IotReadingOrderByRelevanceFieldEnum = {
  id: 'id',
  deviceId: 'deviceId',
  unit: 'unit'
};

exports.Prisma.IotAlertOrderByRelevanceFieldEnum = {
  id: 'id',
  deviceId: 'deviceId',
  ruleId: 'ruleId',
  severity: 'severity',
  message: 'message',
  status: 'status',
  acknowledgedBy: 'acknowledgedBy'
};

exports.Prisma.IotAlertRuleOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  deviceId: 'deviceId',
  parameter: 'parameter',
  operator: 'operator',
  severity: 'severity',
  createdById: 'createdById'
};

exports.Prisma.ToolOrderByRelevanceFieldEnum = {
  id: 'id',
  toolCode: 'toolCode',
  name: 'name',
  description: 'description',
  category: 'category',
  serialNumber: 'serialNumber',
  status: 'status',
  condition: 'condition',
  location: 'location',
  plantId: 'plantId',
  manufacturer: 'manufacturer',
  model: 'model',
  assignedToId: 'assignedToId',
  createdById: 'createdById'
};

exports.Prisma.ToolTransactionOrderByRelevanceFieldEnum = {
  id: 'id',
  toolId: 'toolId',
  type: 'type',
  fromUserId: 'fromUserId',
  toUserId: 'toUserId',
  notes: 'notes',
  performedById: 'performedById'
};

exports.Prisma.InventoryLocationOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  type: 'type',
  address: 'address',
  createdById: 'createdById'
};

exports.Prisma.InventoryAdjustmentOrderByRelevanceFieldEnum = {
  id: 'id',
  adjustmentNumber: 'adjustmentNumber',
  itemId: 'itemId',
  type: 'type',
  reason: 'reason',
  status: 'status',
  approvedById: 'approvedById',
  notes: 'notes',
  createdById: 'createdById'
};

exports.Prisma.InventoryRequestOrderByRelevanceFieldEnum = {
  id: 'id',
  requestNumber: 'requestNumber',
  title: 'title',
  description: 'description',
  status: 'status',
  priority: 'priority',
  requestedById: 'requestedById',
  departmentId: 'departmentId',
  plantId: 'plantId',
  approvedById: 'approvedById',
  notes: 'notes'
};

exports.Prisma.InventoryRequestItemOrderByRelevanceFieldEnum = {
  id: 'id',
  requestId: 'requestId',
  itemId: 'itemId',
  notes: 'notes'
};

exports.Prisma.InventoryTransferOrderByRelevanceFieldEnum = {
  id: 'id',
  transferNumber: 'transferNumber',
  itemId: 'itemId',
  fromLocationId: 'fromLocationId',
  toLocationId: 'toLocationId',
  status: 'status',
  requestedById: 'requestedById',
  approvedById: 'approvedById',
  notes: 'notes'
};

exports.Prisma.SupplierOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  contactPerson: 'contactPerson',
  email: 'email',
  phone: 'phone',
  address: 'address',
  city: 'city',
  country: 'country',
  website: 'website',
  createdById: 'createdById'
};

exports.Prisma.PurchaseOrderOrderByRelevanceFieldEnum = {
  id: 'id',
  poNumber: 'poNumber',
  supplierId: 'supplierId',
  status: 'status',
  priority: 'priority',
  notes: 'notes',
  createdById: 'createdById',
  approvedById: 'approvedById'
};

exports.Prisma.PurchaseOrderItemOrderByRelevanceFieldEnum = {
  id: 'id',
  poId: 'poId',
  itemId: 'itemId',
  description: 'description'
};

exports.Prisma.ReceivingRecordOrderByRelevanceFieldEnum = {
  id: 'id',
  poId: 'poId',
  itemId: 'itemId',
  condition: 'condition',
  receivedById: 'receivedById',
  notes: 'notes'
};

exports.Prisma.SafetyIncidentOrderByRelevanceFieldEnum = {
  id: 'id',
  incidentNumber: 'incidentNumber',
  title: 'title',
  description: 'description',
  type: 'type',
  severity: 'severity',
  status: 'status',
  location: 'location',
  assetId: 'assetId',
  departmentId: 'departmentId',
  plantId: 'plantId',
  reportedById: 'reportedById',
  investigatedById: 'investigatedById',
  rootCause: 'rootCause',
  correctiveAction: 'correctiveAction',
  notes: 'notes'
};

exports.Prisma.SafetyInspectionOrderByRelevanceFieldEnum = {
  id: 'id',
  inspectionNumber: 'inspectionNumber',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  location: 'location',
  departmentId: 'departmentId',
  inspectorId: 'inspectorId',
  findings: 'findings',
  notes: 'notes',
  createdById: 'createdById'
};

exports.Prisma.SafetyTrainingOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  trainer: 'trainer',
  location: 'location',
  attendees: 'attendees',
  notes: 'notes',
  createdById: 'createdById'
};

exports.Prisma.SafetyEquipmentOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  type: 'type',
  status: 'status',
  location: 'location',
  condition: 'condition',
  notes: 'notes',
  createdById: 'createdById'
};

exports.Prisma.SafetyPermitOrderByRelevanceFieldEnum = {
  id: 'id',
  permitNumber: 'permitNumber',
  title: 'title',
  type: 'type',
  status: 'status',
  description: 'description',
  location: 'location',
  requestedById: 'requestedById',
  approvedById: 'approvedById',
  hazardAssessment: 'hazardAssessment',
  precautions: 'precautions',
  notes: 'notes'
};

exports.Prisma.QualityInspectionOrderByRelevanceFieldEnum = {
  id: 'id',
  inspectionNumber: 'inspectionNumber',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  orderId: 'orderId',
  assetId: 'assetId',
  itemId: 'itemId',
  plantId: 'plantId',
  inspectedById: 'inspectedById',
  result: 'result',
  defects: 'defects',
  notes: 'notes'
};

exports.Prisma.NonConformanceReportOrderByRelevanceFieldEnum = {
  id: 'id',
  ncrNumber: 'ncrNumber',
  title: 'title',
  description: 'description',
  severity: 'severity',
  status: 'status',
  type: 'type',
  sourceInspectionId: 'sourceInspectionId',
  assetId: 'assetId',
  itemId: 'itemId',
  departmentId: 'departmentId',
  raisedById: 'raisedById',
  rootCause: 'rootCause',
  correctiveAction: 'correctiveAction',
  notes: 'notes'
};

exports.Prisma.QualityAuditOrderByRelevanceFieldEnum = {
  id: 'id',
  auditNumber: 'auditNumber',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  auditedById: 'auditedById',
  departmentId: 'departmentId',
  scope: 'scope',
  findings: 'findings',
  recommendation: 'recommendation',
  notes: 'notes',
  createdById: 'createdById'
};

exports.Prisma.QualityControlPlanOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  itemId: 'itemId',
  assetId: 'assetId',
  type: 'type',
  frequency: 'frequency',
  characteristics: 'characteristics',
  createdById: 'createdById'
};

exports.Prisma.CorrectiveActionOrderByRelevanceFieldEnum = {
  id: 'id',
  capaNumber: 'capaNumber',
  title: 'title',
  description: 'description',
  type: 'type',
  source: 'source',
  sourceId: 'sourceId',
  severity: 'severity',
  status: 'status',
  rootCause: 'rootCause',
  correctiveAction: 'correctiveAction',
  preventiveAction: 'preventiveAction',
  responsibleId: 'responsibleId',
  verifiedById: 'verifiedById',
  effectiveness: 'effectiveness',
  notes: 'notes'
};

exports.Prisma.SpcProcessOrderByRelevanceFieldEnum = {
  id: 'id',
  processName: 'processName',
  parameter: 'parameter',
  unit: 'unit',
  status: 'status',
  samples: 'samples',
  createdById: 'createdById'
};

exports.Prisma.WorkCenterOrderByRelevanceFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  description: 'description',
  type: 'type',
  status: 'status',
  location: 'location',
  capacityUnit: 'capacityUnit',
  createdById: 'createdById'
};

exports.Prisma.ProductionOrderOrderByRelevanceFieldEnum = {
  id: 'id',
  orderNumber: 'orderNumber',
  title: 'title',
  description: 'description',
  status: 'status',
  priority: 'priority',
  productId: 'productId',
  productName: 'productName',
  workCenterId: 'workCenterId',
  plantId: 'plantId',
  notes: 'notes',
  createdById: 'createdById'
};

exports.Prisma.ProductionBatchOrderByRelevanceFieldEnum = {
  id: 'id',
  batchNumber: 'batchNumber',
  orderId: 'orderId',
  productId: 'productId',
  productName: 'productName',
  status: 'status',
  notes: 'notes',
  createdById: 'createdById'
};

exports.Prisma.MeterReadingOrderByRelevanceFieldEnum = {
  id: 'id',
  readingNumber: 'readingNumber',
  assetId: 'assetId',
  plantId: 'plantId',
  meterName: 'meterName',
  unit: 'unit',
  notes: 'notes',
  readById: 'readById'
};

exports.Prisma.TrainingCourseOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  category: 'category',
  type: 'type',
  status: 'status',
  instructor: 'instructor',
  notes: 'notes',
  createdById: 'createdById'
};

exports.Prisma.ShiftHandoverOrderByRelevanceFieldEnum = {
  id: 'id',
  shiftType: 'shiftType',
  fromShift: 'fromShift',
  toShift: 'toShift',
  departmentId: 'departmentId',
  handedOverById: 'handedOverById',
  receivedById: 'receivedById',
  status: 'status',
  tasksSummary: 'tasksSummary',
  pendingIssues: 'pendingIssues',
  safetyNotes: 'safetyNotes',
  equipmentStatus: 'equipmentStatus',
  notes: 'notes'
};

exports.Prisma.ChecklistOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  type: 'type',
  frequency: 'frequency',
  departmentId: 'departmentId',
  assetId: 'assetId',
  createdById: 'createdById'
};

exports.Prisma.ChecklistItemOrderByRelevanceFieldEnum = {
  id: 'id',
  checklistId: 'checklistId',
  item: 'item',
  description: 'description'
};

exports.Prisma.ChecklistResponseOrderByRelevanceFieldEnum = {
  id: 'id',
  checklistId: 'checklistId',
  completedById: 'completedById',
  status: 'status',
  responses: 'responses',
  notes: 'notes'
};

exports.Prisma.SurveyOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  targetGroup: 'targetGroup',
  questions: 'questions',
  responses: 'responses',
  createdById: 'createdById'
};

exports.Prisma.CalibrationRecordOrderByRelevanceFieldEnum = {
  id: 'id',
  calibrationNumber: 'calibrationNumber',
  title: 'title',
  description: 'description',
  assetId: 'assetId',
  instrumentName: 'instrumentName',
  serialNumber: 'serialNumber',
  status: 'status',
  standardUsed: 'standardUsed',
  result: 'result',
  asFound: 'asFound',
  asLeft: 'asLeft',
  performedById: 'performedById',
  approvedById: 'approvedById',
  notes: 'notes'
};

exports.Prisma.RiskAssessmentOrderByRelevanceFieldEnum = {
  id: 'id',
  assessmentNumber: 'assessmentNumber',
  title: 'title',
  description: 'description',
  assetId: 'assetId',
  departmentId: 'departmentId',
  status: 'status',
  riskLevel: 'riskLevel',
  hazards: 'hazards',
  controls: 'controls',
  residualRisk: 'residualRisk',
  assessorId: 'assessorId',
  reviewerId: 'reviewerId',
  notes: 'notes'
};

exports.Prisma.LotoRecordOrderByRelevanceFieldEnum = {
  id: 'id',
  lotoNumber: 'lotoNumber',
  title: 'title',
  description: 'description',
  assetId: 'assetId',
  departmentId: 'departmentId',
  plantId: 'plantId',
  workOrderId: 'workOrderId',
  lotoType: 'lotoType',
  energySource: 'energySource',
  energySourceDesc: 'energySourceDesc',
  requestedById: 'requestedById',
  supervisorId: 'supervisorId',
  safetyOfficerId: 'safetyOfficerId',
  status: 'status',
  cancelledReason: 'cancelledReason',
  isolationPoints: 'isolationPoints',
  lockDevices: 'lockDevices',
  tagNumbers: 'tagNumbers',
  verifiedBy: 'verifiedBy',
  affectedWorkers: 'affectedWorkers',
  appliedBy: 'appliedBy',
  removedBy: 'removedBy',
  notes: 'notes'
};

exports.Prisma.BillOfMaterialOrderByRelevanceFieldEnum = {
  id: 'id',
  parentId: 'parentId',
  childAssetId: 'childAssetId',
  partNumber: 'partNumber',
  unit: 'unit',
  specification: 'specification',
  status: 'status',
  revision: 'revision',
  notes: 'notes'
};

exports.Prisma.DigitalTwinOrderByRelevanceFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  name: 'name',
  description: 'description',
  type: 'type',
  parameters: 'parameters',
  connections: 'connections',
  specification: 'specification',
  syncInterval: 'syncInterval',
  createdById: 'createdById'
};

exports.Prisma.ConversationOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type'
};

exports.Prisma.ConversationParticipantOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  convoId: 'convoId'
};

exports.Prisma.SessionOrderByRelevanceFieldEnum = {
  id: 'id',
  token: 'token',
  userId: 'userId',
  roles: 'roles',
  permissions: 'permissions'
};

exports.Prisma.ChatMessageOrderByRelevanceFieldEnum = {
  id: 'id',
  convoId: 'convoId',
  senderId: 'senderId',
  content: 'content',
  messageType: 'messageType'
};

exports.Prisma.RepairMaterialRequestOrderByRelevanceFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  itemId: 'itemId',
  itemName: 'itemName',
  unit: 'unit',
  urgency: 'urgency',
  reason: 'reason',
  notes: 'notes',
  status: 'status',
  requestedById: 'requestedById',
  supervisorApprovedById: 'supervisorApprovedById',
  storekeeperApprovedById: 'storekeeperApprovedById',
  issuedById: 'issuedById',
  returnedById: 'returnedById'
};

exports.Prisma.RepairToolRequestOrderByRelevanceFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  toolId: 'toolId',
  toolName: 'toolName',
  reason: 'reason',
  notes: 'notes',
  status: 'status',
  urgency: 'urgency',
  rejectionReason: 'rejectionReason',
  toolConditionAtIssue: 'toolConditionAtIssue',
  toolConditionAtReturn: 'toolConditionAtReturn',
  requestedById: 'requestedById',
  supervisorApprovedById: 'supervisorApprovedById',
  storekeeperApprovedById: 'storekeeperApprovedById',
  issuedById: 'issuedById',
  returnedById: 'returnedById'
};

exports.Prisma.ToolTransferRequestOrderByRelevanceFieldEnum = {
  id: 'id',
  toolId: 'toolId',
  fromUserId: 'fromUserId',
  toUserId: 'toUserId',
  reason: 'reason',
  notes: 'notes',
  status: 'status',
  rejectionReason: 'rejectionReason',
  toolConditionAtTransfer: 'toolConditionAtTransfer',
  requestedById: 'requestedById',
  storekeeperApprovedById: 'storekeeperApprovedById'
};

exports.Prisma.WorkOrderDowntimeOrderByRelevanceFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  assetId: 'assetId',
  assetName: 'assetName',
  reason: 'reason',
  category: 'category',
  impactLevel: 'impactLevel',
  notes: 'notes'
};

exports.Prisma.RepairCompletionOrderByRelevanceFieldEnum = {
  id: 'id',
  workOrderId: 'workOrderId',
  completionNotes: 'completionNotes',
  findings: 'findings',
  rootCause: 'rootCause',
  correctiveAction: 'correctiveAction',
  materialsUsedSummary: 'materialsUsedSummary',
  toolsUsedSummary: 'toolsUsedSummary',
  supervisorReviewNotes: 'supervisorReviewNotes',
  supervisorApprovedById: 'supervisorApprovedById',
  supervisorStatus: 'supervisorStatus',
  reworkReason: 'reworkReason',
  plannerClosedById: 'plannerClosedById',
  plannerStatus: 'plannerStatus',
  closureNotes: 'closureNotes'
};

exports.Prisma.AttachmentOrderByRelevanceFieldEnum = {
  id: 'id',
  fileName: 'fileName',
  fileType: 'fileType',
  filePath: 'filePath',
  entityType: 'entityType',
  entityId: 'entityId',
  uploadedById: 'uploadedById',
  description: 'description'
};


exports.Prisma.ModelName = {
  Role: 'Role',
  Permission: 'Permission',
  RolePermission: 'RolePermission',
  User: 'User',
  UserRole: 'UserRole',
  UserPermission: 'UserPermission',
  SystemModule: 'SystemModule',
  CompanyModule: 'CompanyModule',
  Plant: 'Plant',
  Department: 'Department',
  UserPlant: 'UserPlant',
  MaintenanceRequest: 'MaintenanceRequest',
  WorkOrder: 'WorkOrder',
  WorkOrderTeamMember: 'WorkOrderTeamMember',
  WorkOrderTimeLog: 'WorkOrderTimeLog',
  WorkOrderMaterial: 'WorkOrderMaterial',
  WorkOrderComment: 'WorkOrderComment',
  StatusTransition: 'StatusTransition',
  AuditLog: 'AuditLog',
  EscalationLog: 'EscalationLog',
  CompanyProfile: 'CompanyProfile',
  Notification: 'Notification',
  AssetCategory: 'AssetCategory',
  Asset: 'Asset',
  InventoryItem: 'InventoryItem',
  StockMovement: 'StockMovement',
  PmSchedule: 'PmSchedule',
  PmTemplate: 'PmTemplate',
  PmTemplateTask: 'PmTemplateTask',
  PmTrigger: 'PmTrigger',
  WorkOrderStatusHistory: 'WorkOrderStatusHistory',
  MaintenanceRequestComment: 'MaintenanceRequestComment',
  Trade: 'Trade',
  UserSkill: 'UserSkill',
  IotDevice: 'IotDevice',
  IotReading: 'IotReading',
  IotAlert: 'IotAlert',
  IotAlertRule: 'IotAlertRule',
  Tool: 'Tool',
  ToolTransaction: 'ToolTransaction',
  InventoryLocation: 'InventoryLocation',
  InventoryAdjustment: 'InventoryAdjustment',
  InventoryRequest: 'InventoryRequest',
  InventoryRequestItem: 'InventoryRequestItem',
  InventoryTransfer: 'InventoryTransfer',
  Supplier: 'Supplier',
  PurchaseOrder: 'PurchaseOrder',
  PurchaseOrderItem: 'PurchaseOrderItem',
  ReceivingRecord: 'ReceivingRecord',
  SafetyIncident: 'SafetyIncident',
  SafetyInspection: 'SafetyInspection',
  SafetyTraining: 'SafetyTraining',
  SafetyEquipment: 'SafetyEquipment',
  SafetyPermit: 'SafetyPermit',
  QualityInspection: 'QualityInspection',
  NonConformanceReport: 'NonConformanceReport',
  QualityAudit: 'QualityAudit',
  QualityControlPlan: 'QualityControlPlan',
  CorrectiveAction: 'CorrectiveAction',
  SpcProcess: 'SpcProcess',
  WorkCenter: 'WorkCenter',
  ProductionOrder: 'ProductionOrder',
  ProductionBatch: 'ProductionBatch',
  MeterReading: 'MeterReading',
  TrainingCourse: 'TrainingCourse',
  ShiftHandover: 'ShiftHandover',
  Checklist: 'Checklist',
  ChecklistItem: 'ChecklistItem',
  ChecklistResponse: 'ChecklistResponse',
  Survey: 'Survey',
  CalibrationRecord: 'CalibrationRecord',
  RiskAssessment: 'RiskAssessment',
  LotoRecord: 'LotoRecord',
  BillOfMaterial: 'BillOfMaterial',
  DigitalTwin: 'DigitalTwin',
  Conversation: 'Conversation',
  ConversationParticipant: 'ConversationParticipant',
  Session: 'Session',
  ChatMessage: 'ChatMessage',
  RepairMaterialRequest: 'RepairMaterialRequest',
  RepairToolRequest: 'RepairToolRequest',
  ToolTransferRequest: 'ToolTransferRequest',
  WorkOrderDowntime: 'WorkOrderDowntime',
  RepairCompletion: 'RepairCompletion',
  Attachment: 'Attachment'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
